### ISSUE TITLE
ledger sign error, on Opera 54

### ISSUE THREAD

**Issue by mattkanwisher** [loomnetwork/dashboard#174]
```
Ryan Sean Adams, [Mar 1, 2019 at 2:05:43 AM]:
chunk-vendors.5e080d3f.js:1 Deposit failed, error:  s {name: "TransportStatusError", message: "Ledger device: Invalid data received (0x6a80)", stack: "Error↵    at new s (https://dashboard.dappchains.c…hains.com/js/chunk-vendors.5e080d3f.js:148:369130", statusCode: 27264, statusText: "INCORRECT_DATA"}message: "Ledger device: Invalid data received (0x6a80)"name: "TransportStatusError"stack: "Error↵    at new s (https://dashboard.dappchains.com/js/chunk-vendors.5e080d3f.js:177:99101)↵    at r.<anonymous> (https://dashboard.dappchains.com/js/chunk-vendors.5e080d3f.js:148:370208)↵    at M (https://dashboard.dappchains.com/js/chunk-vendors.5e080d3f.js:111:133700)↵    at Generator._invoke (https://dashboard.dappchains.com/js/chunk-vendors.5e080d3f.js:111:134783)↵    at Generator.t.(anonymous function) [as next] (https://dashboard.dappchains.com/js/chunk-vendors.5e080d3f.js:111:133879)↵    at n (https://dashboard.dappchains.com/js/chunk-vendors.5e080d3f.js:148:369036)↵    at https://dashboard.dappchains.com/js/chunk-vendors.5e080d3f.js:148:369130"statusCode: 27264statusText: "INCORRECT_DATA"__proto__: Error
    at Object.f57d (https://dashboard.dappchains.com/js/chunk-vendors.5e080d3f.js:177:99166)
    at i (https://dashboard.dappchains.com/js/index.53a7675c.js:1:720)
    at Object.<anonymous> (https://dashboard.dappchains.com/js/chunk-vendors.5e080d3f.js:148:368730)
    at Object.d584 (https://dashboard.dappchains.com/js/chunk-vendors.5e080d3f.js:148:373178)
    at i (https://dashboard.dappchains.com/js/index.53a7675c.js:1:720)
    at Object.<anonymous> (https://dashboard.dappchains.com/js/chunk-vendors.5e080d3f.js:106:306348)
    at Object.7fe4 (https://dashboard.dappchains.com/js/chunk-vendors.5e080d3f.js:106:310040)
    at i (https://dashboard.dappchains.com/js/index.53a7675c.js:1:720)
    at Module.b635 (https://dashboard.dappchains.com/js/index.53a7675c.js:1:97361)
    at i (https://dashboard.dappchains.com/js/index.53a7675c.js:1:720)stack: "Error↵    at Object.f57d (https://dashboard.dappchains.com/js/chunk-vendors.5e080d3f.js:177:99166)↵    at i (https://dashboard.dappchains.com/js/index.53a7675c.js:1:720)↵    at Object.<anonymous> (https://dashboard.dappchains.com/js/chunk-vendors.5e080d3f.js:148:368730)↵    at Object.d584 (https://dashboard.dappchains.com/js/chunk-vendors.5e080d3f.js:148:373178)↵    at i (https://dashboard.dappchains.com/js/index.53a7675c.js:1:720)↵    at Object.<anonymous> (https://dashboard.dappchains.com/js/chunk-vendors.5e080d3f.js:106:306348)↵    at Object.7fe4 (https://dashboard.dappchains.com/js/chunk-vendors.5e080d3f.js:106:310040)↵    at i (https://dashboard.dappchains.com/js/index.53a7675c.js:1:720)↵    at Module.b635 (https://dashboard.dappchains.com/js/index.53a7675c.js:1:97361)↵    at i (https://dashboard.dappchains.com/js/index.53a7675c.js:1:720)"__proto__: constructor: ƒ Error()stackTraceLimit: 50arguments: (...)caller: (...)captureStackTrace: ƒ captureStackTrace()length: 1name: "Error"prototype: {constructor: ƒ, name: "Error", message: "", toString: ƒ}__proto__: ƒ ()[[Scopes]]: Scopes[0]message: ""name: "Error"toString: ƒ toString()arguments: (...)caller: (...)length: 0name: "toString"__proto__: ƒ ()[[Scopes]]: Scopes[0]__proto__: Object
t.(anonymous function) @ chunk-vendors.5e080d3f.js:1
a.(anonymous function) @ raven.js:51
(anonymous) @ index.53a7675c.js:1
M @ chunk-vendors.5e080d3f.js:111
(anonymous) @ chunk-vendors.5e080d3f.js:111
t.(anonymous function) @ chunk-vendors.5e080d3f.js:111
o @ chunk-vendors.5e080d3f.js:54
u @ chunk-vendors.5e080d3f.js:54
Promise.then (async)
o @ chunk-vendors.5e080d3f.js:54
s @ chunk-vendors.5e080d3f.js:54
(anonymous) @ chunk-vendors.5e080d3f.js:54
e @ chunk-vendors.5e080d3f.js:81
(anonymous) @ chunk-vendors.5e080d3f.js:54
t @ index.53a7675c.js:1
ie @ chunk-vendors.5e080d3f.js:132
r @ chunk-vendors.5e080d3f.js:132
Po.o._wrapper @ chunk-vendors.5e080d3f.js:132
d @ raven.js:386
i @ chunk-vendors.5e080d3f.js:111

Opera 54: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36 OPR/54.0.2952.64
```

![photo_2019-03-01 02 07 20](https://user-images.githubusercontent.com/3032/53591577-eac73d00-3bc6-11e9-91b2-9121b0b67d37.jpeg)

**Comment by mattkanwisher** [comment]
I saw this might be related https://support.ledger.com/hc/en-us/articles/360007709194

**Comment by mattkanwisher** [comment]
https://github.com/LedgerHQ/ledger-app-eth/issues/43

**Comment by mattkanwisher** [comment]
confirmed working

needed latest firmware, contract data on, display data off - opera
